### ISSUE TITLE
Superagent issue in JSPM based application

### ISSUE THREAD

**Issue by adriatic** [auth0-community/auth0-aurelia-samples#24]
___This issue is extracted from https://github.com/auth0-community/auth0-aurelia-samples/issues/22 for easier tracking___.

**Comment by adriatic** [comment]
The application at https://github.com/aurelia-auth0/model-sample/tree/master/jspm/esnext exhibits the **`req.setNotDelay is not a function,`** that @aaguiarz referred to as

> OK, about the `req.setNotDelay is not a function`, if you can send a small example that reproduces it would be helpful. It seems related to how superagent is loaded.

in **[this comment](https://github.com/auth0-community/auth0-aurelia-samples/issues/22#issuecomment-385289361)**

In order to verify and hopefully solve this problem follow the following steps:

# 1.
Clone the repository https://github.com/aurelia-auth0/model-sample

# 2.
Extract the https://github.com/aurelia-auth0/model-sample/tree/master/jspm/esnext folder

# 3. Build and run
```
npm install
jspm install
gulp watch
```
# 4.
Show in the browser
http:://localhost:9000

# 5. 
Click on **`Login`** or **`Github Users`** (this later one requires authentication, so it "invokes" Login)

![image](https://user-images.githubusercontent.com/2712405/39436862-39e874c0-4c6d-11e8-813e-c41d09f23c0a.png)

# 6.
Use credentials ac-demo@aureliatools.com / (password sent to you via email) to login

# 7.
Observe the returned "hash-fragment" (also sent to you via email) - this is the correct response from auth0.

The chrome console has the following stack trace errors
```
[aurelia] Aurelia Started
bluebird.min.js:31 Unhandled rejection TypeError: req.setNoDelay is not a function
    at Request.request (http://localhost:9000/jspm_packages/npm/superagent@3.8.2/lib/node/index.js:284:9)
    at Request.end (http://localhost:9000/jspm_packages/npm/superagent@3.8.2/lib/node/index.js:366:10)
    at Object.getJWKS (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/helpers/jwks.js:16:29)
    at IdTokenVerifier.getRsaVerifier (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/index.js:108:10)
    at IdTokenVerifier.verify (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/index.js:57:15)
    at WebAuth.validateToken (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:251:12)
    at WebAuth.validateAuthenticationResponse (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:193:15)
    at WebAuth.parseHash (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:159:15)
    at Auth0Service.handleAuthentication (http://localhost:9000/dist/services/auth0-service.js:66:22)
    at App.attached (http://localhost:9000/dist/app.js:84:30)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:3525:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1570:25)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1933:15)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-framework@1.2.0/aurelia-framework.js:206:30)
    at r (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
    at i._settlePromiseFromHandler (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
```
# 8.
Pay attention to the following lines of the stacktrace
```
at Object.getJWKS (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/helpers/jwks.js:16:29)
    at IdTokenVerifier.getRsaVerifier (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/index.js:108:10)
    at IdTokenVerifier.verify (http://localhost:9000/jspm_packages/npm/idtoken-verifier@1.2.0/src/index.js:57:15)
    at WebAuth.validateToken (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:251:12)
    at WebAuth.validateAuthenticationResponse (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:193:15)
    at WebAuth.parseHash (http://localhost:9000/jspm_packages/npm/auth0-js@9.5.0/src/web-auth/index.js:159:15)
    at Auth0Service.handleAuthentication (http://localhost:9000/dist/services/auth0-service.js:66:22)
    at App.attached (http://localhost:9000/dist/app.js:84:30)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:3525:24)
```
 where you can see that the **`handleAuthentication`** was invoked as soon as the app was attached to DOM (this is of course the second invocation of **`handleAuthentication`** that took place when the app was "reset" by the server.

That should suffice to start a solid debugging session 😏  - I would not recommend shrinking this app to a smaller version **which still exhibits the same problem**, as you could easily lose the bug that way. Simply put the breakpoint **[here](https://github.com/aurelia-auth0/model-sample/blob/master/jspm/esnext/src/services/auth0-service.js#L54)** and step through the **`parseHash()`** code, which is likely familiar to you

# My environment

windows 10, node v8.9.4, npm 5.8.0, jspm 0.16.63

**Comment by adriatic** [comment]
Any questions / comments - please add to this thread
